version: '2'
services:
  influxdb:
    build: ./influx
    restart: always
    ports:
     - "8083:8083"
     - "8086:8086"
    environment:
     - INFLUXDB_ADMIN_ENABLED=true
    volumes:
     - influxdb:/var/lib/influxdb
  grafana:
    image: fg2it/grafana-armhf:v4.1.1
    restart: always
    ports: 
     - "3000:3000"
    environment:
     - GF_INSTALL_PLUGINS=neocat-cal-heatmap-panel
    links: 
     - influxdb:influxdb
  ehz-reader:
    build: ./ehz-reader
    restart: always
    links: 
     - influxdb:influxdb
    devices:
     - "/dev/ttyUSB0:/dev/ttyUSB0"
volumes:
 influxdb: